# Change prefix to Ctrl+`
unbind C-b
set -g prefix 'C-`'
bind 'C-`' send-prefix

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Set -g default-terminal screen-256color
set -g status-keys vi
set -g history-limit 10000
set -g mouse on

setw -g mode-keys vi
setw -g monitor-activity on

bind h split-window -h
bind v split-window -v

# Use Ctrl-vim keys without prefix to resize panes
bind -n C-J resize-pane -D 
bind -n C-K resize-pane -U 
bind -n C-H resize-pane -L 
bind -n C-L resize-pane -R 

# Use prefix + t to enter tree mode
unbind s
bind t choose-tree

# Use Ctrl-Alt-vim keys without prefix key to switch panes
bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf